name: Maven-Example

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: '1.11'
        settings-path: "${{ github.workspace }}"
    # - Unsupported parameter 'Settings file' with value '{"class"=>"jenkins.mvn.DefaultSettingsProvider"}'
    # - Unsupported parameter 'Global Settings file' with value 'Use default maven global settings'
    - name: Run maven
      run: mvn -f C:/parent/pom.xml -Dname1=value1 clean site install
